### ISSUE TITLE
Default window position

### ISSUE THREAD

**Issue by kurtandro** [ray-lothian/Layout-Resizer#5]
Hello ray-lothian,
would it be possible to have one window position that is set automatically everytime when Firefox starts up?
Many greetings
Kurt

**Comment by mauriciofaria** [comment]
Hi.
I need this too...

**Comment by ray-lothian** [comment]
Hey guys. We already have this on the options page. Reopen if you need something else

**Comment by ElhemEnohpi** [comment]
@ray-lothian I'm not able to find any "options page" or settings on the Firefox version of the addon. I don't see how to set a default position for new windows.
