### ISSUE TITLE
Issue with multiple monitor setup

### ISSUE THREAD

**Issue by el95149** [ray-lothian/Layout-Resizer#6]
Hi there, thanks for all your great work on this!

My Firefox (on Kubuntu 20.04) just updated the extension to version 0.1.4, and I'm now facing the following issue:
I have a dual monitor setup (laptop 17" on the left, ultrawide 34" on the right).
When I choose one of the presets, the FF window is always moved to the left screen upon resizing, no matter where it first sat.
Before this update it would stay on the screen it originally was, which, at least for me, is the desired functionality.

Thanks for any feedback you may provide.

**Comment by ray-lothian** [comment]
Please wait for 0.1.5 release and give it a try. Reopen if the bug is not fixed.

**Comment by el95149** [comment]
All's well with 0.1.5, thanks a lot for the express fix!
